# Generated by Django 2.2.4 on 2019-09-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190925_0255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='fakepk',
            new_name='uuid',
        ),
    ]
